PHP 8.4 support
flowjs/flow-php-server pull request #53
Opened 2024-12-06 23:14 UTC by phpfui

* Updated composer.json to support PHP 8.0 and higher only
* Moved to testing under GitHub Actions
* Ported to newer PHPUnit
* Added and corrected types for PHP 8.4 support

ToDo:
-----

Unit test need some work, but not sure what to do here as I am not familiar with the code.

2024-12-07 10:45 UTC, AidasK requested changes

2024-12-07 10:45 UTC, AidasK commented on src/Flow/Basic.php
> +    public static function save(string $destination, $config, ?RequestInterface $request = null) : bool
maybe type config as `string|ConfigInterface`

2024-12-07 10:45 UTC, AidasK commented on src/Flow/Config.php
> +		return $this;
not aligned?

2024-12-07 10:45 UTC, AidasK commented on src/Flow/Config.php
> +		return $this;
align?

2024-12-07 10:45 UTC, AidasK commented on src/Flow/Config.php
> +		return $this;
code style

2024-12-07 10:45 UTC, AidasK commented on src/Flow/Mongo/MongoConfig.php
>          $this->gridFs = $gridFS;
remove this?

2024-12-07 10:45 UTC, AidasK commented
Are these tests passing locally?

2024-12-07 13:59 UTC, phpfui commented
Will fix these issues. Maybe I should set up phpcsfixer and phpstan too.

Tests fail for me locally, you will have to fix, as you know the code better. Not sure how the mocking works.

2024-12-07 19:42 UTC, phpfui commented
I fixed the save() parameter type.  Also fixed the formatting with PHP-CS-Fixer.  Corrected a bunch of type errors with PHPStan (removed the MongoConfigInterface, as it is not really needed). I also fixed one of the PHPUnit errors.  The other two are caused by the mocking, but not exactly sure how to fix those, so you will need to work on them.

I am going to test this in my project.  Will push again if I find and fix any issues.  I can't test the MongoDB stuff, as I use SQL only.

2024-12-07 21:12 UTC, phpfui commented
My local testing seems to work with no mods needed.  This should probably be released as v1.3 or v2.0

2024-12-08 20:07 UTC, AidasK commented on src/Flow/Mongo/MongoFile.php
> +            'n' => ((int) $index - 1)
n was probably bool before?

2024-12-09 12:14 UTC, merged

2024-12-09 12:17 UTC, AidasK commented
Released as 2.0, thank you for your contribution <3

2024-12-09 13:41 UTC, phpfui commented
Thanks for the prompt attention. Seems PHP 8.4 compatibility is not a high priority for many maintainers.